server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yzy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: zhiyi123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
#日志输出环境 对应为logback-spring.xml的springProfile的name 目前默认生产环境 输出info级别到控制台和日志文件
  profiles:
    active: prod
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yyq.wedding.domain
  configuration:
    autoRuntimeDialect: true




